name: Check if `setup-python` and `nox` work well togheter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip nox
    - name: Test with nox
      run: |
        nox --report report.json
        cat report.json
